org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.console=plain
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8

loom_version=1.17.11
loader_version=0.19.3

mod_version=1.10.0
maven_group=com.github.charlyb01
archives_base_name=music_control
